import {Tracklist} from './model.ts';
import type {ParsedTrack,VariationType} from './model.ts';
const VARIATION_WORD=/\b(remix|rework|mashup|edit|re-burst|vip|flip|bootleg|mix|dub)\b/i;
function splitPeople(s:string){return s.split(/\s+(?:&|x|vs\.)\s+|\s*&\s*/i).map(x=>x.trim()).filter(Boolean);}
function variationType(text:string):VariationType|undefined { const m=text.match(VARIATION_WORD)?.[1]?.toLowerCase(); if(!m)return; return ({remix:'REMIX',rework:'REWORK',mashup:'MASHUP',edit:'EDIT','re-burst':'RE_BURST',vip:'VIP',flip:'FLIP',bootleg:'BOOTLEG',mix:'MIX',dub:'DUB'} as Record<string,VariationType>)[m]??'OTHER'; }
function parseVariation(version:string|undefined, primary:string[]){ if(!version)return undefined; const type=variationType(version); if(!type)return undefined; if(type==='VIP') return {type,creditArtists:[...primary],sourceText:version}; const suffix=version.match(/^(.*?)\s+(Remix|Rework|Mashup|Edit|Re-burst|Flip|Bootleg|Mix|Dub)$/i); return {type,creditArtists:suffix?splitPeople(suffix[1]):[],sourceText:version}; }
export function parseLine(line:string):ParsedTrack|null{const clean=line.replace(/^\s*\d+[.)]?\s*/, '').trim();if(!clean||!clean.includes(' - '))return null;const [artistText,...rest]=clean.split(' - ');const rawTitle=rest.join(' - ').trim();if(!artistText||!rawTitle||/\s-\sID(?:\s|$)/i.test(` - ${rawTitle}`))return null;
 const feat=artistText.match(/^(.*?)\s+(?:ft\.?|feat\.?)\s+(.+)$/i);const primaryText=(feat?.[1]??artistText).trim();const featuredText=feat?.[2]?.trim();
 const primary=splitPeople(primaryText), featured=featuredText?splitPeople(featuredText):[];
 const paren=rawTitle.match(/^(.*?)\s*\(([^()]*)\)\s*\*?$/); const title=(paren?.[1]??rawTitle).replace(/\s+\*$/,'').trim(); const version=paren?.[2]?.trim(); const variation=parseVariation(version,primary);
 const assumptions=[`artist names are unique`,`& / x / vs. join primary artists`,`ft./feat. marks featured credit`,`parenthetical text names a playable version`,...(variation?[`${variation.type} is a VariationType`]:version?[`version kind is not interpreted`]:[])];
 const signals:string[]=[]; if(version && !variation) signals.push(`VERSION_UNINTERPRETED: ${version}`); if(version?.includes('/')) signals.push(`VERSION_COMPOSITE: ${version}`); if(variation && variation.type!=='VIP' && variation.creditArtists.length===0) signals.push(`VARIATION_ATTRIBUTION_UNRESOLVED: ${version}`); return {source:line,artistText,title,version,primary,featured,variation,assumptions,signals};}
export function parseTracklist(text:string,playedBy='Unknown'):Tracklist{const entries:ParsedTrack[]=[];const rejected:string[]=[];for(const line of text.split(/\r?\n/)){if(!line.trim())continue;const p=parseLine(line);if(p)entries.push(p);else rejected.push(line);}return new Tracklist(playedBy,entries,rejected);}
